### ISSUE TITLE
Detect event in multiple guestures

### ISSUE THREAD

**Issue by codehimanshu** [mlyknown/vue-gesture#9]
<vue2-gesture :types="['swipeLeft','swipeRight']"  :call="handleComponent.bind(this,'EVENT')">

In my Handle Component, the str will recieve a string 'EVENT' but how can I get the event, that is if the user swiped left or swiped right and perform different action based on that.

**Comment by bees4ever** [comment]
Hi @codehimanshu ,
I don't know how your code looks like, the event you want to have, you can send it from the vue-gesture element, otherwise I may have to update this plugin. So what I mean is this.

Defining your handle method only with an event parameter:
````
handleComponent: function(e){
            console.log(e);
            var html = e.srcElement.innerHTML;
        }
````

Then one can bind the fired event 

`````
<vue2-gesture :types="['swipeDown','click']"   :call="handleComponent.bind(this)" >swipeDown and click</vue2-gesture>
`````


And then the event is given back to the handler.

You also can paste you code here. I will not have so much time, but I try to answer asap.

//bees4ever

**Comment by codehimanshu** [comment]
Both the events are working but what I want is to perform different actions on different gestures.
This is what I came up with:
```
  <vue2-gesture :type="'swipeLeft'"  :call="handleComponent.bind(this,'swipeLeft')">
    <vue2-gesture :type="'swipeRight'"  :call="handleComponent.bind(this,'swipeRight')">
      Multiple Guesture
    </vue2-gesture>
  </vue2-gesture>
```
```
        handleComponent: function(str,e){
          if(str=="swipeRight"){
            console.log("Right Swiped")
          }
          if(str=="swipeLeft"){
            console.log("Left Swiped")
          }
        }
```

**Comment by bees4ever** [comment]
Ok... this worked for me... You may can try this, or what exactly it the error, does just happen nothing?


[example2.html.zip](https://github.com/mlyknown/vue-gesture/files/2179274/example2.html.zip)

**Comment by codehimanshu** [comment]
That is what I meant, using 2 vue-gestures works for me. But I thought there would be a way, we could do this using a single vue-gesture element and adding multiple gestures and actions.

Thanks a lot for your time.
